### ISSUE TITLE
Problemas al añadir una migracion 

### ISSUE THREAD

**Issue by kennyangelfib** [oriolcatasus/PES_Fibness-backend#3]
He creado una nueva migracion pero me falla al querer la integrarla. 
El comando que he realizado fue:
> npm run migrate up

El resultado que obtengo es :
```
could not connect to postgres: { Error: connect ECONNREFUSED 127.0.0.1:5432 
      at TCPconectWrap.afterConnect [as oncomplete](net.js:1107:14)
  errno:  'ECONNREFUSED',
  code:  'ECONNREFUSED',
  syscall: 'connect',
  adress: '127.0.0.1',
  port:5432 }
could not connect to postgres: Error: Client has already been connected. You cannot reuse a client,
     at Client._connect ( ...)
     ...
Client has already been connected. You cannot reuse a client.
     at Client._connect ( ...)
Error: connect ECONNREFUSED 127.0.0.1:5432 
      at TCPconectWrap.afterConnect [as oncomplete](net.js:1107:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibness-backend@1.0.0-alpha1 migrate: `node-pg-migrate -j=sql "up"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibness-backend@1.0.0-alpha1 migrate script
npm ERR! This is probably not a problem with npm.There is likely additional logging output above.
...
```

**Comment by oriolcatasus** [comment]
Okey, el problema era que se había cambiado la forma de obtener las credenciales de la base de datos pero en las migraciones por linea de comandos se seguía usando la forma antigua.

Al principio se accedia a las credenciales en algunas partes con variables de entornos y en otras con ficheros de configuracion, para hacerlo más uniforme y facilitar la seguridad y cambiabilidad de las credenciales ahora se hace siempre a traves de variables de entorno.
